"""Correspondances entre les nuances politiques des fichiers du CDSP et les
partis tels qu'ils sont affichés dans le modèle {{Résultats électoraux}}.

Deux formats coexistent dans les fichiers du CDSP :

* 1958-1981 : une colonne par nuance politique (``COM``, ``SFIO``, ``UNR``...).
  Voir :data:`NUANCES_ANCIENNES`.
* 1988-2012 : une colonne « nuance » et une colonne « Etiquette liste » par
  candidat. La nuance suffit pour les grands partis (:data:`PARTIS_RECENTS`,
  :data:`COULEURS_RECENTES`) ; pour les nuances « fourre-tout » (divers droite,
  extrême gauche...), le parti est déduit de l'étiquette
  (:data:`ETIQUETTES`, :data:`COULEURS_ETIQUETTES`).

Les couleurs sont les codes acceptés par le modèle
{{Infobox Parti politique français/couleurs}} (sans le tiret initial).
"""

MODELE_COULEUR = "{{{{Infobox Parti politique français/couleurs|-{}}}}}"

# Valeur de l'étiquette lorsque la colonne « Etiquette liste » est vide.
ETIQUETTE_VIDE = "empty"


# --- Élections de 1958 à 1981 ---------------------------------------------

# Nom de colonne -> (libellé wiki, code couleur)
NUANCES_ANCIENNES = {
    "COM": ("[[Parti communiste français|PCF]]", "PCF"),
    "COM2": ("[[Apparentement|app.]] [[Parti communiste français|PCF]]", "COM"),
    "UFD": ("[[Union des forces démocratiques (France)|UFD]]", "UFD"),
    "SFIO": ("[[Section française de l'Internationale ouvrière|SFIO]]", "SFIO"),
    "RADSOC": ("[[Parti radical (France)|RADSOC]]", "DVG"),
    "RADICAUX GAUCHE": ("[[Parti radical (France)|RADSOC]]", "DVG"),
    "RADCENT": ("Radicaux centristes", "DVG"),
    "RADUFD": ("Radicaux de l'[[Union des forces démocratiques (France)|UFD]]", "UFD"),
    "UDSRMIN": ("[[Union démocratique et socialiste de la Résistance|UDSR]]", "UDSR"),
    "UNR": ("[[Union pour la nouvelle République|UNR]]", "UNR"),
    "CRR": ("[[Centre républicain|CR]]", "DVD"),
    "DIVGAUL": ("Divers gaullistes", "DVD"),
    "MRP": ("[[Mouvement républicain populaire|MRP]]", "MRP"),
    "MRPVREP": ("[[Mouvement républicain populaire|MRP]]", "MRP"),
    "CNI": ("[[Centre national des indépendants et paysans|CNIP]]", "CNIP"),
    "MOD": ("[[Républicains modérés|Modérés]]", "DVD"),
    "EXD": ("[[Extrême droite en France|EXD]]", "EXD"),
    "POUJ": ("[[Poujadisme|Poujadistes]]", "DVD"),
    "DIV": ("Divers", "DIV"),
    "PSU": ("[[Parti socialiste unifié (France)|PSU]]", "PSU"),
    "EXG": ("[[Extrême gauche en France|EXG]]", "EXG"),
    "UNR-UDT": ("[[Union pour la nouvelle République|UNR-UDT]]", "UNR"),
    "INDVREP": ("[[Fédération nationale des républicains indépendants|RI]]", "RI"),
    "FGDS": ("[[Fédération de la gauche démocrate et socialiste|FGDS]]", "FGDS"),
    "RADDROIT": ("Radicaux de droite", "DVD"),
    "UDR": ("[[Union des démocrates pour la République|UDR]]", "UDR"),
    "RALLIE": ("[[Centre démocratie et progrès|CDP]]", "CDP"),
    "CDP": ("[[Centre démocratie et progrès|CDP]]", "CDP"),
    "ALLREP": ("[[Alliance républicaine pour les libertés et le progrès|AR]]", "DVD"),
    "RIUDR": ("[[Fédération nationale des républicains indépendants|RI]]-[[Union des démocrates pour la République|UDR]]", "UDR"),
    "TD": ("Technique et démocratie", "DIV"),
    "MDR": ("[[Mouvement des réformateurs|MR]]", "DIV"),
    "REG": ("[[Régionalisme (politique)|REG]]", "REG"),
    "DIVMAJ": ("[[Divers droite|DVD]]", "DVD"),
    "DVD": ("[[Divers droite|DVD]]", "DVD"),
    "LO": ("[[Lutte ouvrière|LO]]", "LO"),
    "LCR": ("[[Ligue communiste révolutionnaire|LCR]]", "LCR"),
    "OCR": ("[[Organisation communiste révolutionnaire|OCR]]", "COM"),
    "SOC": ("[[Parti socialiste (France)|PS]]", "PS"),
    "MRG": ("[[Parti radical de gauche|MRG]]", "PRG"),
    "DVG": ("[[Divers gauche|DVG]]", "DVG"),
    "REFRAD": ("Radicaux réformateurs", "DVG"),
    "DIVREF": ("Divers réformateurs", "DIV"),
    "UDRURP": ("[[Union des démocrates pour la République|UDR]]-[[Union des républicains de progrès|URP]]", "UDR"),
    "RIURP": ("[[Fédération nationale des républicains indépendants|RI]]-[[Union des républicains de progrès|URP]]", "RI"),
    "CDURP": ("[[Centre démocrate (France)|CD]]-[[Union des républicains de progrès|URP]]", "CD"),
    "CDPURP": ("[[Centre démocrate (France)|CD]]-[[Union des républicains de progrès|URP]]", "CD"),
    "DIVURP": ("Divers [[Union des républicains de progrès|URP]]", "DVD"),
    "FRONT": ("Front Autogestionnaire", "EXG"),
    "PSMRG": ("[[Parti socialiste (France)|PS]]-[[Parti radical de gauche|PRG]]", "PS"),
    "ECO": ("[[Écologie politique|ECO]]", "ECO"),
    "GAULOPP": ("Gaullistes d'opposition", "DIV"),
    "UDF": ("[[Union pour la démocratie française|UDF]]", "UDF"),
    "RPR": ("[[Rassemblement pour la République|RPR]]", "RPR"),
    "FRN": ("[[Rassemblement national|FN]]", "FN"),
    "UDF-RPR": ("[[Union pour la démocratie française|UDF]]-[[Rassemblement pour la République|RPR]]", "UDF"),
    "CENTDEM": ("[[Centre démocrate (France)|CD]]", "CD"),
    "OCI": ("[[Organisation communiste révolutionnaire|OCI]]", "COM"),
    "RI": ("[[Fédération nationale des républicains indépendants|RI]]", "RI"),
}


# --- Élections de 1988 à 2012 ---------------------------------------------

# Préfixes de nuance traités avant tout le reste : préfixe -> (libellé, couleur)
PREFIXES_SPECIAUX = {
    "MODEM": ("[[Mouvement démocrate (France)|MODEM]]", "MODEM"),
    "NouvC": ("[[Les Centristes|LC]]", "NC"),
    "PSLE": ("[[Les Centristes|PSLE]]", "LC"),
}

# Nuance (3 premières lettres) -> libellé wiki
PARTIS_RECENTS = {
    "ECI": "{{abréviation|DIV|Divers}}",
    "PRV": "[[Parti radical (France)|PRV]]",
    "MAJ": "Majorité Présidentielle",
    "FRN": "[[Rassemblement national|FN]]",
    "VEC": "[[Les Verts (France)|LV]]",
    "GEC": "[[Génération écologie|GE]]",
    "UDF": "[[Union pour la démocratie française|UDF]]",
    "RPR": "[[Rassemblement pour la République|RPR]]",
    "PRG": "[[Parti radical de gauche|PRG]]",
    "RDG": "[[Parti radical de gauche|PRG]]",
    "SOC": "[[Parti socialiste (France)|PS]]",
    "SCO": "[[Parti socialiste (France)|PS]]",
    "SDC": "[[Parti socialiste (France)|PS]]",
    "UMP": "[[Union pour un mouvement populaire|UMP]]",
    "UDR": "[[Union des démocrates pour la République|UDR]]",
    "FDG": "[[Front de gauche (France)|FDG]]",
}

# Nuance (3 premières lettres) -> code couleur
COULEURS_RECENTES = {
    "FDG": "FG",
    "UMP": "UMP",
    "UDR": "UDR",
    "SOC": "SOC",
    "PRG": "PRG",
    "RDG": "PRG",
    "RPR": "RPR",
    "UDF": "UDF",
    "GEC": "GE",
    "SDC": "PS",
    "VEC": "Verts",
    "FRN": "FN",
    "MAJ": "DIV",
    "ECI": "DIV",
    "PRV": "PR",
    "REG": "REG",
    "EXO": "EXD",
}

# Nuance -> {étiquette : libellé wiki}.
# Une étiquette absente de la table est affichée telle quelle.
ETIQUETTES = {
    "EXO": {
        "empty": "Error",
        "Parti ouvrier européen": "[[Parti ouvrier européen|POE]]",
    },
    "REG": {
        "empty": "[[Régionalisme (politique)|REG]]",
        "Regionalistes": "[[Régionalisme (politique)|REG]]",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Unitat Catalana": "[[Unitat Catalana|UC]]",
        "Abertzaleen Batasuna": "[[Abertzaleen Batasuna|AB]]",
        "Union Du Peuple Alsacien": "[[Union du peuple alsacien|UPA]]",
        "Abertzale Nationaliste Basque": "[[Abertzaleen Batasuna|AB]]",
        "Alsace D'Abord, Pour L'Europe Des Regions": "[[Alsace d'abord|AA]]",
        "Alsace D'Abord": "[[Alsace d'abord|AA]]",
        "Erc (Esquarra Republicana Catalana)": "[[Gauche républicaine de Catalogne|GRC]]",
        "Ea Cusko Alkartasuna": "{{abréviation|ECA|Ea Cusko Alkartasuna}}",
        "Domiens Et Tomiens De L'Ile-De-France": "{{abréviation|DTIF|Domiens et tomiens de l'Ile-de-France}}",
        "La Radio Des Alsaciens 107 4 Mhz": "{{abréviation|RA107.4|La radio des alsaciens 107.4 Mhz}}",
        "Radio Alsaciens 107 4 Mhz": "{{abréviation|RA107.4|La radio des alsaciens 107.4 Mhz}}",
        "Entente Des Ecologistes, Les Verts": "{{abréviation|EE|Entente des écologistes}}-[[Les Verts (France)|LV]]",
    },
    "EXG": {
        "empty": "[[Extrême gauche en France|EXG]]",
        "Divers": "[[Extrême gauche en France|EXG]]",
        "Communistes": "[[Communisme|COM]]",
        "Ecologie": "[[Écologisme|ECO]]",
        "Lutte Ouvrière": "[[Lutte ouvrière|LO]]",
        "Lutte Ouvriere": "[[Lutte ouvrière|LO]]",
        "Lutte Ouvriere ": "[[Lutte ouvrière|LO]]",
        "Parti Humaniste": "[[Parti humaniste (France)|PH]]",
        "Combat Ouvrier": "[[Combat ouvrier|CO]]",
        "Candidate Du Parti Humaniste": "[[Parti humaniste (France)|PH]]",
        "Alternative Democratie Socialisme": "[[Convention pour une alternative progressiste|ADS]]",
        "Candidat De Lutte Ouvriere": "[[Lutte ouvrière|LO]]",
        "Ligue Communiste Revolutionnaire": "[[Ligue communiste révolutionnaire|LCR]]",
        "Ligue Communiste Revolutionnaire (Dissident)": "{{abréviation|diss|dissident}} [[Ligue communiste révolutionnaire|LCR]]",
        "Nouveau Parti Anticapitaliste": "[[Nouveau Parti anticapitaliste|NPA]]",
        "Alternatifs (Solidarite, Ecologie, Gauche Alternative)": "[[Les Alternatifs]]",
        "Gauche Alternative Et Ecologiste": "[[Les Alternatifs]]",
        "Les Alternatifs": "[[Les Alternatifs]]",
        "Extreme Gauche": "[[Extrême gauche en France|EXG]]",
        "Extrême gauche": "[[Extrême gauche en France|EXG]]",
        "Parti Socialiste": "[[Extrême gauche en France|EXG]]",
        "Parti Pour La Décroissance": "[[Parti pour la décroissance|PPLD]]",
        "Parti Des Travailleurs": "[[Parti des travailleurs (France)|PT]]",
        "Parti Des Travailâ­Leurs": "[[Parti des travailleurs (France)|PT]]",
        "Mouvement De La Gauche Progressiste": "[[Mouvement de la gauche progressiste|MGP]]",
        "Gauche Alternative 2007": "[[Gauche alternative 2007|GP2007]]",
        "A Gauche Autrement, Sega (Solidarite, Ecologie, Gauche Alternative)": "{{abréviation|GA|A gauche autrement}}-[[Gauche alternative 2007|GP2007]]",
        "Alternative Rouge Et Verte": "[[Alternative rouge et verte|ARV]]",
        "Ligue Trotskiste": "[[Ligue trotskiste de France|LT]]",
        "Mouvement Pour Un Parti Des Travailleurs (Mppt)": "[[Mouvement pour un parti des travailleurs|MPPT]]",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Solidarite, Ecologie, Gauche Alternative (Sega)": "[[Gauche alternative 2007|SEGA]]",
        "Solidarite Ecologie Gauche Alternative (Sega)": "[[Gauche alternative 2007|SEGA]]",
        "Solidarite, Ecologie Gauche Alternative": "[[Gauche alternative 2007|SEGA]]",
        "Solidarite Ecologie Gauche Alternative": "[[Gauche alternative 2007|SEGA]]",
        "Solidarite Ecologie, Gauche Alternative": "[[Gauche alternative 2007|SEGA]]",
        "Solidarite Ecologie ,Gauche Alternative": "[[Gauche alternative 2007|SEGA]]",
        "Solidarite Ecologie, Gauche Alternative Economie Gestion": "[[Gauche alternative 2007|SEGA]]",
        "Parti Des Objecteurs De Croissance": "[[Décroissance]]",
        "Mouvement Ecologiste De L'Anjou, Solidarite, Ecologie Gauche Alternative (Sega)": "{{abréviation|MEA|Mouvement Ecologiste de l'Anjou}}-[[Gauche alternative 2007|SEGA]]",
        "Candidat D Initiative Pour Une Nouvelle Politique A Gauche": "{{abréviation|CINPG|Candidat d'initiative pour une nouvelle politique à gauche}}",
        "Mouvement Alternative Pour La Democratie Et Le Socialisme Communistes Reconstructeurs": "{{abréviation|MADSCR|Mouvement Alternative pour la Démocratie et le Socialisme Communistes Reconstructeurs}}",
        "Voix Des Travailleurs": "[[Voix des travailleurs|VdT]]",
        "Les Alternatifs-Ecologie-Autogestion": "[[Les Alternatifs]]-Ecologie-Autogestion",
        "Gauche Alternative 2012": "{{abréviation|GA2012|Gauche Alternative 2012}}",
        "Union Democratique Populaire Pour Le Res": "{{abréviation|UDP|Union Démocratique Populaire}}",
        "A Gauche Autrement": "{{abréviation|GA|A Gauche Autrement}}",
        "Alliance Ecologique": "{{abréviation|AE|Alliance Ecologique}}",
        "Parti Mystico Rationaliste Guadeloupeen": "{{abréviation|PMRG|Parti mystico rationaliste guadeloupéen}}",
        "Association 93 Au Coeur": "{{abréviation|A93C|Association 93 au coeur}}",
        "Candidate D Initiative Pour Une Nouvelle Politique A Gauche": "{{abréviation|INPG|Initiative pour une nouvelle politique à gauche}}",
        "Front Autogestionnaire": "{{abréviation|FA|Front Autogestionnaire}}",
        "Rassemblement Unite Paix": "{{abréviation|RUP|Rassemblement Unité Paix}}",
        "Mouvement Pour La Sauvegarde De La Vie Associative Et Culturelle": "{{abréviation|MSVAC|Mouvement pour la Sauvegarde de la Vie Associative et Culturelle}}",
        "Gauche Revolutionnaire": "{{abréviation|GR|Gauche Révolutionnaire}}",
        "Vraiment A Gauche Autrement": "{{abréviation|VGA|Vraiment à gauche autrement}}",
        "Parti Des Chomeurs Et Des Mecontents": "{{abréviation|CM|Parti des chômeurs et des mécontents}}",
        "Opposition Ouvriere": "{{abréviation|OO|Opposition Ouvrière}}",
        "Nous Sommes La Gauche": "{{abréviation|SG|Nous sommes la gauche}}",
        "Comite Chomeurs-Salaries D'Alfortville-Vitry": "{{abréviation|CCSAV|Comité chomeurs-salariés d'Alfortville-Vitry}}",
        "Ligue Socialiste Des Travailleurs": "{{abréviation|LST|Ligue Socialiste des Travailleurs}}",
        "Ecologie Pacifisme Objection De Croissance": "{{abréviation|EPOC|Écologie pacifisme objection de croissance}}",
        "Changer A Gauche": "{{abréviation|CG|Changer à gauche}}",
        "Alliance Liberale Et Sociale": "{{abréviation|ALS|Alliance Libérale et Sociale}}",
        "Nouvelle Solidarite": "{{abréviation|NS|Nouvelle Solidarité}}",
        "Rassemblement Pour La Democratie Et Le Civisme": "{{abréviation|RDC|Rassemblement pour la démocratie et le civisme}}",
        "Comite Pour La Defense Du Regime Local": "{{abréviation|CDRL|Comite pour la défense du régime local}}",
        "Candidatures Unitaires Antiliberales 79": "{{abréviation|UA79|Unitaires Antiliberales 79}}",
        "Tous Ensemble A Gauche": "{{abréviation|TEG|Tous ensemble à gauche}}",
        "Collectif Antiliberal Du Pays De Lorient": "{{abréviation|CG|Collectif antilibéral du pays de Lorient}}",
        "100% A Gauche - Lcr": "{{abréviation|100%|100% à gauche}}-[[Ligue communiste révolutionnaire|LCR]]",
        "L.C.R. 100% A Gauche": "{{abréviation|100%|100% à gauche}}-[[Ligue communiste révolutionnaire|LCR]]",
        "Union Pour L'Ecologie Et La Democratie": "{{abréviation|UED|Union pour l'écologie et la démocratie}}",
        "Autogestion Soutenu Par Les Verts": "{{abréviation|ALV|Autogestion soutenu par Les Verts}}",
        "Anjou Ecologie Autogestion": "{{abréviation|AEA|Anjou Ecologie Autogestion}}",
        "A Gauche Toute Collectif Pour Une Gauc": "{{abréviation|GCG|A Gauche toute Collectif pour une Gauche}}",
        "Pole Rennaissance Communiste En France": "[[Pôle de renaissance communiste en France|PRCF]]",
        "Union Pour La Gauche Renovee": "{{abréviation|UGR|Union pour la gauche rénovée}}",
        "Initiative Pour Une Nouvelle Politique Gauche": "{{abréviation|INPG|Initiative pour une nouvelle politique à gauche}}",
        "Initiative Pour Une Nouvelle Politique A Gauche": "{{abréviation|INPG|Initiative pour une nouvelle politique à gauche}}",
        "Candidat D Initiative Pour Une Nouvelle Politique De Gauche": "{{abréviation|INPG|Initiative pour une nouvelle politique gauche}}",
        "Parti Ouvrier Indépendant": "[[Parti ouvrier indépendant|POI]]",
        "A Gauche Vraiment": "{{abréviation|GV|A gauche vraiment}}",
        "Ecologie Autogestion": "{{abréviation|EA|Ecologie Autogestion}}",
        "Mouvement A Gauche Vraiment ": "{{abréviation|MGV|Mouvement à gauche Vraiment}}",
        "Solidarite Ecologie": "{{abréviation|SE|Solidarité Ecologie}}",
        "Candidat Pour Le Droit A La Difference": "{{abréviation|CDD|Candidat pour le droit à la différence}}",
        "Vert Et Rouge": "{{abréviation|VR|Vert et Rouge}}",
        "Gauche 92 Cap": "{{abréviation|G92C|Gauche 92 Cap}}",
        "Gauche 92": "{{abréviation|G92|Gauche 92}}",
        "Gauche 92 Les Alternatifs": "[[Les Alternatifs]]",
        "Parti De Gauche Dissident": "{{abréviation|diss.|dissident}} [[Parti de gauche (France)|PG]]",
        "Gauche Citoyenne Et Ecologiste": "{{abréviation|GCE|Gauche Citoyenne et Ecologiste}}",
        "Mouvement A Gauche Vraiment": "{{abréviation|GV|A gauche vraiment}}",
        "Gauche Unitaire Et Antiliberale": "{{abréviation|GUA|Gauche Unitaire et Antilibérale}}",
        "Gauche Unie Antiliberale": "{{abréviation|GUA|Gauche Unie Antilibérale}}",
        "Gauche Alternative": "{{abréviation|GA|Gauche Alternative}}",
        "Yvelines Décroissance": "{{abréviation|YD|Yvelines Décroissance}}",
        "Ecologie A Gauche Vraiment": "{{abréviation|EGV|Ecologie à Gauche Vraiment}}",
        "Candidat Se Declarant Antimilitariste": "{{abréviation|AM|Antimilitariste}}",
        "Moral Politic": "{{abréviation|MP|Moral Politic}}",
        "Comite D Initiative Pour Une Nouvelle Politique A Gauche": "{{abréviation|CINPG|Comité d'initiative pour une nouvelle politique à gauche}}",
        "Parti Des Evidences Concretes": "{{abréviation|PEC|Parti des Évidences Concrètes}}",
        "Pour Une Nouvelle Politique A Gauche": "{{abréviation|NPG|Pour une nouvelle politique à gauche}}",
        "Pour L Initiative Pour Une Nouvelle Politique A Gauche": "{{abréviation|NPG|Pour l'initiative pour une nouvelle politique à gauche}}",
        "Rassemblement Utile A Tous": "{{abréviation|RUT|Rassemblement utile à tous}}",
    },
    "DVD": {
        "empty": "[[Divers droite|DVD]]",
        "Independante": "Indépendante",
        "Divers Droite Et Independant": "[[Divers droite|DVD]]",
        "Union Pour Un Mouvement Populaire": "[[Union pour un mouvement populaire|UMP]]",
        "Union Pour La Majorite Presidentielle": "[[Union pour un mouvement populaire|UMP]]",
        "Parti Republicain": "[[Parti républicain (France)|PR]]",
        "Mouvement Pour La France": "[[Mouvement pour la France|MPF]]-[[Union pour un mouvement populaire|UMP]]",
        "Mouvement Pour La France (Soutien Ump)": "[[Mouvement pour la France|MPF]]",
        "Debout La République": "[[Debout la France|DLR]]",
        "Royaliste": "[[Royalisme|Royaliste]]",
        "Debout La Republique": "[[Debout la France|DLR]]",
        "Royaliste D Action Francaise": "[[Action française|AF]]",
        "Moselle Debout Rpr-Udf-Cnip": "{{abréviation|MD|Moselle Debout}}-[[Centre national des indépendants et paysans|CNIP]]-[[Union pour la démocratie française|UDF]]-[[Rassemblement pour la République|RPR]]",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Sans Étiquette": "[[Sans étiquette|SE]]",
        "Objectif Guadeloupe": "[[Objectif Guadeloupe|OG]]",
        "Federation Du Rassemblement Pour La Republique: Objectif Guadeloupe": "[[Objectif Guadeloupe|OG]]",
        "Sans Étiquette (Soutien Ump Et Prv)": "[[Sans étiquette|SE]] ([[Union pour un mouvement populaire|UMP]]-[[Parti républicain (France)|PR]])",
        "Membre Du Centre National Des Independants": "[[Centre national des indépendants et paysans|CNI]]",
        "Centre National Des Independants Et Paysans": "[[Centre national des indépendants et paysans|CNIP]]",
        "Centre National Des Indépendants Et Paysans": "[[Centre national des indépendants et paysans|CNIP]]",
        "Centre National Des Independants Et Paysans (Cni)": "[[Centre national des indépendants et paysans|CNIP]]",
        "Centre National Des Independants Et Paysans (Cnip)": "[[Centre national des indépendants et paysans|CNIP]]",
        "Centre National Des Independants Et Paysans Cni": "[[Centre national des indépendants et paysans|CNIP]]",
        "Cnip": "[[Centre national des indépendants et paysans|CNIP]]",
        "Centre National Des Independants": "[[Centre national des indépendants et paysans|CNI]]",
        "Democratie Chretienne Cni": "{{abréviation|DC|Démocratie Chrétienne}} [[Centre national des indépendants et paysans|CNI]]",
        "Droite De Conviction Pour La Defense Des Valeurs": "{{abréviation|DCDV|Droite de conviction pour la défense des valeurs}}",
        "Droite De Conviction Pour La Defense Des Valeurs Presente Par Le Centre National Des Independants Et Paysans Cni": "{{abréviation|DCDV|Droite de conviction pour la défense des valeurs}}-[[Centre national des indépendants et paysans|CNI]]",
        "Droite De Conviction Pour La Defense Des Valeurs Presente Par Le Centre National Des Independants Et Paysans (Cni) Et La Democratie Chretienne Francaise (Dcf)": "{{abréviation|DCDV|Droite de conviction pour la défense des valeurs}}-[[Centre national des indépendants et paysans|CNI]]-{{abréviation|DCF|Démocratie Chrétienne Française}}",
        "Droite De Conviction Pour La Defense Des Valeurs Presente Par Le Centre National Des Independants Et Paysans Et La Democratie Chretienne Francaise": "{{abréviation|DCDV|Droite de conviction pour la défense des valeurs}}-[[Centre national des indépendants et paysans|CNI]]-{{abréviation|DCF|Démocratie Chrétienne Française}}",
        "Droite De Conviction Pour La Defense Des Valeurs, Presente Par Le Centre National Des Independants Et Paysans, Cni, Et La Democratie Chretienne Francaise": "{{abréviation|DCDV|Droite de conviction pour la défense des valeurs}}-[[Centre national des indépendants et paysans|CNI]]-{{abréviation|DCF|Démocratie Chrétienne Française}}",
        "Parti Chrétien-Démocrate": "[[VIA, la voie du peuple|PCD]]",
        "Union Républicaine Populaire": "[[Union populaire républicaine (2007)|UPR]]",
        "Divers Droite": "[[Divers droite|DVD]]",
        "Majoritepresidentielle Dvd Cni": "[[Divers droite|DVD]]-[[Centre national des indépendants et paysans|CNI]]",
        "Lyon Divers Droite (Soutien Pcd Et Mpf)": "[[Divers droite|DVD]]",
        "Lyon Divers Droite": "[[Divers droite|DVD]]",
        "La Droite Independante (Mpf)": "[[La droite indépendante|LDI]]",
        "Rassemblement Pour La France": "[[Rassemblement pour la France|RPF]]",
        "Mouvement Des Reformateur": "[[Mouvement des réformateurs|MR]]",
        "Parti Libéral Démocrate": "[[Parti libéral démocrate (France)|PLD]]",
        "Union Des Démocrates Pour La République": "[[Union des démocrates pour la République|UDR]]",
        "Mouvement De M. Jeannou Lacaze Candidat Union Des Democrates": "[[Union des démocrates pour la République|UDR]]",
        "Rassemblement Pour La Republique": "[[Rassemblement pour la République|RPR]]",
        "Divers Droite, Union Pour Une Future Majorite Parlementaire Qui Prenne En Compte Les Interets Du Boulonnais": "[[Divers droite|DVD]]",
        "Union Pour La France (Rpr, Udf, Cni)": "[[Rassemblement pour la République|RPR]]-[[Union pour la démocratie française|UDF]]-[[Centre national des indépendants et paysans|CNI]]",
        "Union De L'Opposition Udf-Rpr": "[[Union pour la démocratie française|UDF]]-[[Rassemblement pour la République|RPR]]",
        "Renouveau Du Mantois, Centre National Des Independants Et Paysans": "{{abréviation|RM|Renouveau du Mantois}} [[Centre national des indépendants et paysans|CNIP]]",
        "Udf Dissident": "{{abréviation|diss.|dissident}} [[Union pour la démocratie française|UDF]]",
        "Union Pour Un Mouvement Populaire (Dissident)": "{{abréviation|diss.|dissident}} [[Union pour un mouvement populaire|UMP]]",
        "Ump Dissident": "{{abréviation|diss.|dissident}} [[Union pour un mouvement populaire|UMP]]",
        "Ump Dissidente": "{{abréviation|diss.|dissident}} [[Union pour un mouvement populaire|UMP]]",
        "Majorite Presidentielle - Rpr": "[[Rassemblement pour la République|RPR]]",
        "Rpr Dissident": "{{abréviation|diss.|dissident}} [[Rassemblement pour la République|RPR]]",
        "Rassemblement Pour La Republique Dissident": "{{abréviation|diss.|dissident}} [[Rassemblement pour la République|RPR]]",
        "Droite Liberale Chretienne": "[[Droite libérale-chrétienne|DLC]]",
        "Alternative Liberale": "[[Alternative libérale|AL]]",
        "Alliance Royale": "[[Alliance royale|AR]]",
        "Parti De La Loi Naturelle": "[[Parti de la loi naturelle|PLN]]",
        "Candidat Du Parti Democrate Francais": "[[Parti démocrate français|PDF]]",
        "Le Trefle - Les Nouveaux Ecologistes": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Union De La Droite Republicaine": "Union de la droite republicaine",
        "Mouvement Des Reformateurs": "[[Mouvement des réformateurs|MDR]]",
        "Mouvements Des Reformateurs": "[[Mouvement des réformateurs|MDR]]",
        "Entente Centriste": "{{abréviation|EC|Entente Centriste}}",
        "Union de la droite republicaine": "{{abréviation|UDR|Union de la droite républicaine}}",
        "Guadeloup Doubout": "{{abréviation|GD|Guadeloup Doubout}}",
        "La Nouvelle Majorite Parti Democrate Francais": "{{abréviation|NMDF|La nouvelle majorité parti démocrate francais}}",
        "Rassemblement Pour Une Veritable Ouverture Sociale Et Liberale": "{{abréviation|RVOSL|Rassemblement pour une véritable ouverture sociale et libérale}}",
        "Liste D Union Centriste Pour Montreuil": "{{abréviation|UCM|Liste d'union centriste pour Montreuil}}",
        "Renouveau Centriste": "{{abréviation|RC|Renouveau Centriste}}",
        "Rassemblement Des Centristes Et Des Democrates Sociaux De La Gaudeloupe": "{{abréviation|RCDSG|Rassemblement des centristes et des démocrates sociaux de la Gaudeloupe}}",
        "Candidat Independant": "{{abréviation|CI|Candidat Indépendant}}",
        "Union Pour Le Changement": "{{abréviation|UC|Union pour le Changement}}",
        "Parti Régionaliste Martiniquais": "{{abréviation|PRM|Parti Régionaliste Martiniquais}}",
        "Independant Apolitique": "{{abréviation|IA|Indépendant Apolitique}}",
        "Union Du Rassemblement De La Droite": "{{abréviation|URD|Union du Rassemblement de la Droite}}",
        "Foute Fe Pour La Guadeloupe": "{{abréviation|TFG|Foute Fe pour la Guadeloupe}}",
        "Independant Pour Le Val-De-Marne ": "{{abréviation|IVM|Indépendant pour le Val-de-Marne}}",
        "Pour Une Politique Francaise Aux Dom Tom": "{{abréviation|PFDT|Pour une politique francaise dux Dom Tom}}",
        "Union Locale Pour Une Meilleure Existence": "{{abréviation|ULME|Union locale pour une meilleure existence}}",
        "Union Pour La France": "{{abréviation|UF|Union pour la France}}",
        "Union Centriste Liberale": "{{abréviation|UCL|Union Centriste Libérale}}",
        "Pour L Avenir D Aubervilliers La Courneuve Et Le Bourget": "{{abréviation|AACB|Pour l'avenir d'Aubervilliers la Courneuve et le Bourget}}",
        "Temps Nouveau": "{{abréviation|TN|Temps Nouveau}}",
        "Esprit Civique, Le Gaullisme En Mouvement": "{{abréviation|ECGM|Esprit civique, le gaullisme en mouvement}}",
        "Mouvement Social Democrate": "{{abréviation|MSD|Mouvement Social Démocrate}}",
        "Centre Chretien Populaire": "{{abréviation|CCP|Centre Chretien Populaire}}",
        "Candidat Independant D'Opposition": "{{abréviation|CIO|Candidat Indépendant d'Opposition}}",
        "Candidature Liberale": "{{abréviation|CL|Candidature Libérale}}",
        "Union Pour La Vendée": "{{abréviation|UV|Union pour la Vendée}}",
        "Majorite President Dl Union Droite": "{{abréviation|UD|Union Droite}}",
        "Pour Une Nouvelle Majorite Presidentielle": "{{abréviation|NMP|Nouvelle Majorité Présidentielle}}",
        "Le Centre": "{{abréviation|LC|Le Centre}}",
        "Candidat D'Union Contre La Gauche": "{{abréviation|CUCG|Candidat d'union contre la gauche}}",
        "Centre Et Democratie": "{{abréviation|CD|Centre et démocratie}}",
        "Alternative Region Mantaise": "{{abréviation|ARM|Alternative Région Mantaise}}",
        "Association Des Usagers De L'Administration": "{{abréviation|AUA|Association des usagers de l'administration}}",
        "Candidate Presentee Par L'Union Des Independants": "{{abréviation|UI|Union des Indépendants}}",
        "Entente Souverainiste": "{{abréviation|ES|Entente Souverainiste}}",
        "Appel Du 7 Mai Pour L'Union De La Majorite Presidentielle": "{{abréviation|MP|Appel du 7 Mai pour l'union de la Majorité Présidentielle}}",
        "Union De La Droite En Mouvement": "{{abréviation|UDM|Union de la Droite en Mouvement}}",
        "Candidat Pour La Defense Du 14 Eme": "{{abréviation|D14|Candidat pour la défense du 14éme}}",
        "Union De La Jeunesse Et Des Createurs": "{{abréviation|UJC|Union de la Jeunesse et des Créateurs}}",
        "Candidat Republicain Du Beaujolais": "{{abréviation|CRB|Candidat républicain du Beaujolais}}",
        "Alliance Radicale Et Centriste": "{{abréviation|ARC|Alliance radicale et centriste}}",
        "Union Centriste Liberale Et Republicaine": "{{abréviation|UCLR|Union Centriste Libérale et Républicaine}}",
        "Objectif Decroissance": "{{abréviation|OD|Objectif Décroissance}}",
        "Union Democratique Au Service Des Citoyens": "{{abréviation|UDSC|Union démocratique au service des citoyens}}",
        "Rassemblement Des Democrates Et Republicains De Progres": "{{abréviation|RDRP|Rassemblement des démocrates et républicains de progrès}}",
        "Union Gaulliste Progres": "{{abréviation|UGP|Union Gaulliste Progrès}}",
        "Pour Faire Gagner L'Opposition ": "{{abréviation|GO|Pour faire gagner l'opposition}}",
        "Kinesitherapeute": "Kinésithérapeute",
        "République Solidaire": "{{abréviation|RS|République Solidaire}}",
        "Divers Droite France Francaise": "{{abréviation|DDFF|Divers droite France francaise}}",
        "Candidate Gaulliste Pour Le Rassemblement De La Droite": "{{abréviation|GRD|Candidate gaulliste pour le rassemblement de la droite}}",
        "Parti Picard Democrate": "{{abréviation|PPD|Parti Picard Démocrate}}",
        "Union France Democratie": "{{abréviation|UFD|Union France Démocratie}}",
        "Parti Des Francophones": "{{abréviation|PF|Parti des Francophones}}",
        "Democrate Du Centre Libre": "{{abréviation|DCL|Démocrate du centre libre}}",
        "Rassemblement Democrate Et Liberal": "{{abréviation|RDL|Rassemblement Démocrate et Libéral}}",
        "Pour Un Vrai Changement Liberal": "{{abréviation|VCL|Pour un vrai changement libéral}}",
        "Aujourd'Hui, Autrement": "{{abréviation|AA|Aujourd'Hui, Autrement}}",
        "Rassemblement Social Et Liberal": "{{abréviation|RSL|Rassemblement Social et Libéral}}",
        "Comite L Alsace Merite Mieux": "{{abréviation|CAMM|Comite l'Alsace mérite mieux}}",
        "Rassemblement Des Democrates Et Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des démocrates et des républicains de progrès}}",
        "Union Pour La Democratie Francaise Dissident": "{{abréviation|UDFD|Union pour la démocratie française dissident}}",
        "Pour L Union Des Partis Politiques Francais": "{{abréviation|UPPF|Pour l'union des partis politiques francais}}",
        "Federation Des Independants Du Bas Rhin Cin": "{{abréviation|FIBR|Fédération des indépendants du Bas-Rhin}}",
        "Cand. Indept  Defense Du Monde Rural": "{{abréviation|CIDMR|Candidat Indépendent défense du monde rural}}",
        "Union Centriste Republicaine": "{{abréviation|UCR|Union Centriste Républicaine}}",
        "Ensemble, L'An 2000": "{{abréviation|EA2000|Ensemble, l'an 2000}}",
        "Independant De L'Opposition": "{{abréviation|IO|Indépendant de l'opposition}}",
        "Rassemblement Pour L'Independance De L'Europe": "{{abréviation|RIE|Rassemblement pour l'indépendance de l'Europe}}",
        "Dvd Union De La Droite - Mp": "{{abréviation|UD-MP|Union de la droite - MP}}",
        "Reagir Pour Reussir Candidat D'Opposition": "{{abréviation|RRCO|Réagir pour réussir candidat d'opposition}}",
        "Union Centriste": "{{abréviation|UC|Union Centriste}}",
        "Rassemblement Des Independants": "{{abréviation|RI|Rassemblement des indépendants}}",
        "Rassemblement Des Democrates Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des démocrates des républicains de progrès}}",
        "Parti Blanc": "{{abréviation|PB|Parti Blanc}}",
        "Union Nationale Des Electeurs": "{{abréviation|UNE|Union Nationale des Electeurs}}",
        "Independant D'Opposition": "{{abréviation|IO|Indépendant d'opposition}}",
        "Union Royaliste": "{{abréviation|UR|Union Royaliste}}",
        "Mouvement Servir": "{{abréviation|MS|Mouvement Servir}}",
        "Mouvement France Regions (Mfr)": "{{abréviation|MFR|Mouvement France Régions}}",
        "Union De Rassemblement Et Du Centre": "{{abréviation|URC|Union de Rassemblement et du Centre}}",
        "Moselle Debout, Nouvelle Generation Lorraine": "{{abréviation|MDNGL|Moselle Debout, Nouvelle Génération Lorraine}}",
        "Gaulliste De Progres Social": "{{abréviation|GPS|Gaulliste de progrés social}}",
        "Droite Independant": "{{abréviation|DI|Droite Indépendant}}",
        "Union Des Producteurs De Porc Des Pyrenees Altlantiques": "{{abréviation|UPPPA|Union des producteurs de porc des Pyrénées-Altlantiques}}",
        "Union Des Producteurs De Porcs Des Pyrenees Atlantiques": "{{abréviation|UPPPA|Union des producteurs de porc des Pyrénées-Altlantiques}}",
        "Democratie Permanente": "{{abréviation|DP|Démocratie permanente}}",
        "Delegue General De La Chambre De Commerce Et D'Industrie De Paris": "{{abréviation|DGCCIP|Délégué Général de la chambre de commerce et d'industrie de Paris}}",
        "Union Pour Une Politique Nouvelle": "{{abréviation|UPN|Union pour une Politique Nouvelle}}",
        "Association De Defense Des Locataires": "{{abréviation|ADL|Association de Défense des Locataires}}",
        "Parti Pour La Liberte": "{{abréviation|PL|Parti pour la liberté}}",
        "Valeur D'Inspiration Chrétienne, Sociale, Écologique Et Diversité": "{{abréviation|VICSED|Valeur d'inspiration chrétienne, sociale, écologique et diversité}}",
        "Centriste De Progres": "{{abréviation|CP|Centriste de progrès}}",
        "Morale Politique Verite": "{{abréviation|MPV|Morale Politique Vérité}}",
        "Gaulliste D`Opposition Nationale": "{{abréviation|GON|Gaulliste d'Opposition Nationale}}",
        "Independant Pour Une Lorraine Forte": "{{abréviation|ILF|Independant pour une Lorraine forte}}",
        "Independant De Droite": "{{abréviation|ID|Indépendant de droite}}",
        "Gaulliste Social": "{{abréviation|GS|Gaulliste Social}}",
        "Union De L'Opposition Des Gaullistes Et Divers Droites": "{{abréviation|UOGDD|Union de l'opposition des gaullistes et divers droites}}",
        "Droite Unifiee": "{{abréviation|DU|Droite Unifiée}}",
        "Rhône Divers Droite": "{{abréviation|RDD|Rhône Divers Droite}}",
        "Divers Droite Liberale Et Sociale": "{{abréviation|DDLS|Divers droite libérale et sociale}}",
        "Union Nationale Republicaine": "{{abréviation|UNR|Union Nationale Républicaine}}",
        "Parti Liberal Chretien": "{{abréviation|PLC|Parti Libéral Chretien}}",
        "Mouvement Democrate Francais": "{{abréviation|MDF|Mouvement Démocrate Français}}",
        "Ecologiste - Divers Gauche": "{{abréviation|EDVG|Ecologiste - Divers Gauche}}",
        "Mouvement Des Democrates": "{{abréviation|MD|Mouvement des démocrates}}",
        "Gaulliste Independant": "{{abréviation|GI|Gaulliste Indépendant}}",
        "Pour La Justice Et La Prosperite De La France": "{{abréviation|JPF|Pour la justice et la prospérité de la France}}",
        "Union Des Independants": "{{abréviation|UI|Union des Indépendants}}",
        "Candidat Presente Par L'Union Des Independants Mouvement De M. Jeannou Lacaze": "{{abréviation|UI|Union des Indépendants}}",
        "Cap Liberte Egalite Fraternite": "{{abréviation|CLEF|Cap Liberté Egalité Fraternité}}",
        "Union Du Rassemblement Et Du Centre": "{{abréviation|URC|Union du rassemblement et du centre}}",
    },
    "DVG": {
        "Divers Gauche": "[[Divers gauche|DVG]]",
        "empty": "[[Divers gauche|DVG]]",
        "Pole Republicain": "[[Pôle républicain|PR]]",
        "Pole Republicain Outre Mer": "[[Pôle républicain|PR]]",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Sans Étiquette": "[[Sans étiquette|SE]]",
        "Bâtir Le Pays Martinique": "{{abréviation|GD|Guadeloup Doubout}}",
        "Gauche Moderne": "[[La Gauche moderne|GM]]",
        "Rassemblement Démocratrique Martiniquais": "[[Rassemblement démocratique pour la Martinique|RDM]]",
        "Mouvement Republicain Et Citoyen": "[[Mouvement républicain et citoyen|MRC]]",
        "Mouvement Republicain Et Citoyen (Soutien Ps)": "[[Mouvement républicain et citoyen|MRC]]",
        "Socialiste Dissidente": "[[Dissidence|diss]] [[Parti socialiste (France)|PS]]",
        "Parti Socialiste (Dissident)": "[[Dissidence|diss]] [[Parti socialiste (France)|PS]]",
        "Pour La Semaine De 4 Jours": "[[Semaine de quatre jours|Pour la semaine de 4 jours]]",
        "Mouvement Des Citoyens": "[[Mouvement des citoyens (France)|MDC]]",
        "Mouvement Des Citoyens Soutien Parti Communiste Francais": "[[Mouvement des citoyens (France)|MDC]]-[[Parti communiste français|PCF]]",
        "Energie Radicale": "[[Mouvement des citoyens (France)|MDC]]",
        "Mouvement Républicain Et Citoyen": "[[Mouvement républicain et citoyen|MRC]]",
        "Parti Socialiste": "[[Parti socialiste (France)|PS]]",
        "Regions Et Peuples Solidaires": "[[Régions et peuples solidaires|RPS]]",
        "Pole Republicain Et Udf": "[[Pôle républicain|PR]]-[[Union pour la démocratie française|UDF]]",
        "Divers Gauche Et Centre": "[[Divers gauche|DVG]]",
        "Guadeloupe Unie Socialisme Et Realites": "[[Guadeloupe unie, solidaire et responsable|GU]]",
        "Parti Progressiste Et Democratique Guadeloupeen": "[[Parti progressiste démocratique guadeloupéen|PPDG]]",
        "Guadeloupe Unie Socialisme Et Realites Dissident": "{{abréviation|diss.|dissident}} [[Guadeloupe unie, solidaire et responsable|GU]]",
        "Federation Guadeloupeenne Du Parti Socialiste Dissident": "{{abréviation|diss.|dissident}} [[Fédération guadeloupéenne du Parti socialiste|FGPS]]",
        "Parti Socialiste Guadeloupeen": "[[Fédération guadeloupéenne du Parti socialiste|PSG]]",
        "Dissident Parti Radical De Gauche": "{{abréviation|diss.|dissident}} [[Parti radical de gauche|PRG]]",
        "Gauche Plurielle / Parti Socialiste": "{{abréviation|GP|Gauche Plurielle}}-[[Parti socialiste (France)|PS]]",
        "Parti Socialiste Dissident": "{{abréviation|diss.|dissident}} [[Parti socialiste (France)|PS]]",
        "Rassemblement Pour Initiative Citoyenne": "{{abréviation|RIC|Rassemblement pour l'initiative citoyenne}}",
        "Clichy Reconciliee": "{{abréviation|CR|Clichy Réconciliée}}",
        "Mouv Rassemblement Soc-Dem-Rep": "{{abréviation|SOC-DEM-REP|Mouvement Rassemblement Soc-Dem-Rep}}",
        "Union Victimes De L'Etat": "{{abréviation|UVE|Union Victimes de l'Etat}}",
        "Parti De L'Union Radicale": "{{abréviation|UR|Union Radicale}}",
        "Groupe Bouillantais De Reflexion Et D'Action Sociale": "{{abréviation|GBRAS|Groupe bouillantais de réflexion et d'action sociale}}",
        "Collectif Des Inkoruptibles": "{{abréviation|CI|Collectif des Inkoruptibles}}",
        "Parti Des Citoyens Guadeloupeens": "{{abréviation|PCG|Parti des citoyens Guadeloupéens}}",
        "Gauche Plurielle / Parti Progressiste": "{{abréviation|GP-PP|Gauche Plurielle - Parti Progressiste}}",
        "Cap A Gauche": "{{abréviation|CG|Cap à Gauche}}",
        "L'Action": "L'action",
        "L'Action, Divers Gauche": "L'action",
        "Rassemblement De La Gauche Pour Resister": "{{abréviation|RGR|Rassemblement de la gauche pour résister}}",
        "Rassemblemt Des Citoyens Pour Le Progres": "{{abréviation|RCP|Rassemblement des citoyens pour le progrès}}",
        "Mouvement Republique Et Democratie": "{{abréviation|MRD|Mouvement république et démocratie}}",
        "Alternative Democratie Socialisme": "{{abréviation|ADS|Alternative Démocratie Socialisme}}",
        "Republique Et Democratie": "{{abréviation|RD|République et démocratie}}",
        "Candidat Antiliberal De Rassemblement": "{{abréviation|AR|Antilibéral de rassemblement}}",
        "Force Libertes": "{{abréviation|FL|Force Libertés}}",
        "Gauche Plurielle": "{{abréviation|GP|Gauche Plurielle}}",
        "Mars-Gauche Republicaine": "{{abréviation|MGR|Mars-Gauche Républicaine}}",
        "Mouvement Democratie Alsacienne": "{{abréviation|MDA|Mouvement Démocratie Alsacienne}}",
        "Republicain De Progres": "{{abréviation|RP|Républicain de Progrés}}",
        "Mouvement Inter-Culturel": "{{abréviation|MIC|Mouvement inter-culturel}}",
        "Gauche Solidaire": "{{abréviation|GS|Gauche Solidaire}}",
        "Guadeloup Doubout": "{{abréviation|GD|Guadeloup Doubout}}",
        "Nofwap La Guadeloupe En Action": "{{abréviation|NGA|Nofwap la Guadeloupe en action}}",
        "Union Des Independants Et Paysans": "{{abréviation|UIP|Union des indépendants et paysans}}",
        "Avenir Et Citoyennete": "{{abréviation|AC|Avenir et citoyenneté}}",
        "Mouvement Guadeloupeen Ecologiste": "{{abréviation|MGE|Mouvement Guadeloupéen Ecologiste}}",
        "Socialiste Dissident": "{{abréviation|SD|Socialiste Dissident}}",
        "Gauche Progressiste": "{{abréviation|GP|Gauche Progressiste}}",
        "Citoyennete Pour Tous De Maine-Et-Loire": "{{abréviation|CML|Citoyennete pour tous de Maine-et-Loire}}",
        "Candidat Des Forces De Gauche, Ecologistes Et Republicains De Progres": "{{abréviation|CFGERP|Candidat des Forces de Gauche, Ecologistes et Républicains de Progrés}}",
        "Gauche Independante": "{{abréviation|GI|Gauche indépendante}}",
        "Gaulliste De Gauche": "{{abréviation|GG|Gaulliste de Gauche}}",
        "Nouvelle Gauche": "{{abréviation|NG|Nouvelle Gauche}}",
        "La France A Tous Les Francais": "{{abréviation|FF|La France à tous les français}}",
        "Parti Des Forces Radicales": "{{abréviation|FR|Parti des Forces Radicales}}",
        "Nouvelle Vague - Dvg": "{{abréviation|NV-DVG|Nouvelle Vague - DVG}}",
        "La Force Salarienne": "{{abréviation|FS|La Force Salarienne}}",
        "Centre Gauche": "{{abréviation|CG|Centre Gauche}}",
        "Alternative Unitaire Antiliberale": "{{abréviation|AUA|Alternative Unitaire Antilibérale}}",
        "Gauche Nouvelle, Audacieuse, Realiste": "{{abréviation|GNAR|Gauche Nouvelle, Audacieuse, Réaliste}}",
        "Carrefour Des Gauches": "{{abréviation|CG|Carrefour des gauches}}",
        "Gauche Ouvriere Et Chretienne": "{{abréviation|GOC|Gauche ouvrière et chrétienne}}",
        "Convention Pour Une Alternative Progressive": "{{abréviation|CAP|Convention pour une alternative progressive}}",
        "Citoyens En Mouvement": "{{abréviation|CM|Citoyens en Mouvement}}",
        "Mouvement Democratie Lorraine": "{{abréviation|MDL|Mouvement Démocratie Lorraine}}",
        "Renouveau A Gauche": "{{abréviation|RG|Renouveau à Gauche}}",
        "A Gauche Vraiment": "{{abréviation|GV|A Gauche Vraiment}}",
        "Initiative Republicaine": "{{abréviation|IR|Initiative républicaine}}",
    },
    "DIV": {
        "empty": "Divers",
        "Le Trefle - Les Nouveaux Ecologistes": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Nouveaux Ecologistes": "[[Le Trèfle - Les nouveaux écologistes|NE]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Hommes Nature Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Representante Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Nouveaux Ecologistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecoloâ­Gistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecoâ­Logistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveau Ecologistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux, Union Nationale Ecologiste": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux, Presentes Par L'Union Nationale Ecologiste, Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux Presentes Par L'Union Nationale Ecologiste, Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux Presente Par L'Union Nationale Ecologiste Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste Union Nationale Ecologiste": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux Presentes Par L'Union Nationale Ecologiste Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux Agent De Service Hospitalier": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux ": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Parti De La Loi Naturelle": "[[Parti de la loi naturelle|PLN]]",
        "La Loi Naturelle": "[[Parti de la loi naturelle|PLN]]",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Sans Étiquette": "[[Sans étiquette|SE]]",
        "Mouvement Indépendantiste Martiniquais": "[[Mouvement indépendantiste martiniquais|MIM]]",
        "Euskal Herria Bai": "[[Euskal Herria Bai|EHBai]]",
        "Esquerra Republicana De Catalunya": "[[Gauche républicaine de Catalogne|GRC]]",
        "Batasuna": "[[Batasuna]]",
        "Mouvement Regionaliste Alsace D'Abord": "[[Alsace d'abord|AA]]",
        "Unitat Catalana": "[[Unitat Catalana|UC]]",
        "Convergence Democratique De Catalogne": "[[Convergence démocratique de Catalogne|UDC]]",
        "Parti Nationaliste Basque": "[[Parti nationaliste basque (France)|PNB]]",
        "Chasse Peche Nature Traditions": "[[Le Mouvement de la ruralité|CPNT]]",
        "Chasse Peche Nature Et Traditions": "[[Le Mouvement de la ruralité|CPNT]]",
        "Parti Federaliste": "[[Parti fédéraliste (France)|PF]]",
        "Parti Fédéraliste Européen": "[[Parti fédéraliste (France)|PF]]",
        "Regions Et Peuples Solidaires": "[[Solidarité et progrès|SP]]",
        "Solidarité Et Progrès": "[[Solidarité et progrès|SP]]",
        "Solidarite Et Progres": "[[Solidarité et progrès|SP]]",
        "Parti Humaniste": "[[Parti humaniste (France)|PH]]",
        "Parti Pour La Decroissance": "[[Parti pour la décroissance|PD]]",
        "Rassemblement Des Contribuables Francais": "[[Nicolas Miguet|Rassemblement des contribuables francais]]",
        "Parti Rachid Nekkaz": "[[Rachid Nekkaz|Parti Rachid Nekkaz]]",
        "Parti Occitan": "[[Partit occitan|PO]]",
        "Gaulliste": "[[Gaullisme|Gaulliste]]",
        "Abertzaleen Batasuna": "[[Abertzaleen Batasuna|AB]]",
        "Parti Breton": "[[Parti breton|PB]]",
        "Generation Ecologie": "[[Génération écologie|GE]]",
        "Energies Democrates": "[[Christian Blanc|Energies democrates]]",
        "Les Verts Ecologie": "[[Les Verts (France)|LV]]",
        "Apparentee Les Verts": "{{abréviation|app.|apparentée}}-[[Les Verts (France)|LV]]",
        "Udf - Mouvement Democrate": "[[Union pour la démocratie française|UDF]]-[[Mouvement démocrate (France)|MODEM]]",
        "Union Pour La Raison Au Pouvoir": "{{abréviation|URP|Union pour la Raison au Pouvoir}}",
        "Partit Per Catalunya": "{{abréviation|PC|Partit Per Catalunya}}",
        "Centre Independant": "{{abréviation|CI|Centre Indépendant}}",
        "Union Ecologistes Hauts-De-Seine": "{{abréviation|UEHS|Union Ecologistes Hauts-de-Seine}}",
        "Union Des Ecologistes Independants": "{{abréviation|UEI|Union des écologistes indépendants}}",
        "Cent Couleurs": "{{abréviation|CC|Cent Couleurs}}",
        "Parti Democrate Chretien Guadeloupeen": "{{abréviation|PDCG|Parti démocrate chrétien guadeloupéen}}",
        "Bien Vivre Dans Nos Communes": "{{abréviation|BVC|Bien Vivre dans nos Communes}}",
        "Parti Des Génovéfains": "{{abréviation|Génovéfains|Parti des Génovéfains}}",
        "Collectif Des Democrates Handicapes": "{{abréviation|CDH|Collectif des Démocrates Handicapés}}",
        "Yvelines Ecologie": "{{abréviation|YE|Yvelines Ecologie}}",
        "Parti Union Justice Et Travail": "{{abréviation|UJT|Parti Union Justice et Travail}}",
        "Sos Papa": "{{abréviation|SP|Sos Papa}}",
        "Union Victimes De L'Etat": "{{abréviation|UVE|Union Victimes de l'Etat}}",
        "Union Action": "{{abréviation|UA|Union Action}}",
        "Guadeloupe Nature Et Environnement": "{{abréviation|GNE|Guadeloupe Nature et Environnement}}",
        "Independantiste": "Indépendantiste",
        "Professionnels De Sante": "{{abréviation|PS|Professionnels de santé}}",
        "Parti De La Politique Interculturelle": "{{abréviation|PPI|Parti de la politique interculturelle}}",
        "Rdc-Mdr": "RDC-MDR",
        "Mouvement Citoyennete Democratie": "{{abréviation|MCD|Mouvement Citoyenneté Démocratie}}",
        "Cannabis Santé Libertés Justice": "{{abréviation|CSLJ|Cannabis Santé Libertés Justice}}",
        "La France De Demain": "{{abréviation|FD|La France de demain}}",
        "Ecologie Et Laicite - Ecologie 92 Animateur Assoc. Coop. Et Mouvements Communautaires Ingenieur": "{{abréviation|EL|Ecologie et Laïcité}}-{{abréviation|E92|Ecologie 92 Animateur Assoc. Coop.}}-{{abréviation|MCI|Mouvements Communautaires Ingénieur}}",
        "Oxygene Clichy-Levallois": "{{abréviation|OCL|Oxygene Clichy-Levallois}}",
        "Equilibre Et Environnement (Collectif Associatif Pour La Sauvegarde De L'Environnement)": "{{abréviation|EE|Équilibre et Environnement}}",
        "Force Libertes": "{{abréviation|FL|Force Libertés}}",
        "Couleur Citoyenne": "{{abréviation|CC|Couleur Citoyenne}}",
        "Souverainete Ecologie Ruralite": "{{abréviation|SER|Souveraineté Ecologie Ruralité}}",
        "S.O.S. Papa": "{{abréviation|SP|Sos Papa}}",
        "Ecologie Active": "{{abréviation|EA|Ecologie active}}",
        "M.I.G.U.E.T. Maintenant !": "{{abréviation|M.I.G.U.E.T|M.I.G.U.E.T. Maintenant !}}",
        "Ensemble Aujourd'Hui Mouvement Politique Des Droits Civiques": "{{abréviation|EAMPDC|Ensemble aujourd'hui mouvement politique des droits civiques}}",
        "Mouvement Democrate": "{{abréviation|MD|Mouvement Démocrate}}",
        "Ligue Socialiste Des Travailleurs": "{{abréviation|LST|Ligue Socialiste des Travailleurs}}",
        "Vraie Liberte D'Expression": "{{abréviation|VLE|Vraie Liberté d'Expression}}",
        "Union Europeenne Des Retraites Rattachee A L'Union Des Independants": "{{abréviation|UERUI|Union européenne des retraites rattachée à l'union des indépendants}}",
        "Alliance Reformatrice": "{{abréviation|AR|Alliance Réformatrice}}",
        "Union Des Independants": "{{abréviation|UI|Union des indépendants}}",
        "L'Enfant Et Son Droit": "{{abréviation|ED|L'enfant et son droit}}",
        "Moment D’Agir": "{{abréviation|MA|Moment d'agir}}",
        "Atout Direct": "{{abréviation|AD|Atout Direct}}",
        "Walwari": "Walwari",
        "Democratie Locale": "{{abréviation|DL|Démocratie Locale}}",
        "Divers réformateurs": "{{abréviation|DR|Divers réformateurs}}",
        "Ecologie Independante Et Associative Dites Le Vertement": "{{abréviation|EIAV|Ecologie indépendante et associative dites le vertement}}",
        "Moins D Impot Gerer Utilement L Emploi P": "{{abréviation|MIGUE|Moins d'impot gérer utilement l'emploi}}",
        "Front Liberation Des Oisifs Proletariens": "{{abréviation|FLOP|Front libération des oisifs prolétariens}}",
        "Parti Unitaire Républicain": "{{abréviation|UR|Parti Unitaire Républicain}}",
        "Ecologie Solidarite": "{{abréviation|ES|Ecologie Solidarité}}",
        "Ecologiste Solidarite": "{{abréviation|ES|Ecologie Solidarité}}",
        "Gouvernement De La France": "{{abréviation|GF|Gouvernement de la France}}",
        "L'Alliance Pour L'Ecologie Et La Democratie Francecologie": "{{abréviation|AEDF|L'alliance pour l'écologie et la démocratie Francecologie}}",
        "Ameliorer Votre Quotidien": "{{abréviation|AQ|Ameliorer votre quotidien}}",
        "Entente Des Ecologistes": "{{abréviation|EE|Entente des écologistes}}",
        "Le Bonheur Est A Asnieres Et Colombes": "{{abréviation|BAC|Le bonheur est à Asnières et Colombes}}",
        "Union Elargie Des Seniors": "{{abréviation|UES|Union élargie des séniors}}",
        "Parti Des Musulmans De France": "{{abréviation|PMF|Parti des musulmans de France}}",
        "Rassemblement Francais D'Outre-Mer Emigre En France Et Sympathisant": "{{abréviation|RFOEFS|Rassemblement francais d'outre-mer émigré en France et sympathisant}}",
        "Ecologie, Pluraliste Et Independant": "{{abréviation|EPI|Ecologie, Pluraliste et Indépendant}}",
        "Democrate Europeen": "{{abréviation|DE|Démocrate Européen}}",
        "Mouvement Progressiste Europeen": "{{abréviation|MPE|Mouvement progressiste européen}}",
        "C.E.S.P.R.I.M.E.R  Autrement": "{{abréviation|CESPRIMERA|C.E.S.P.R.I.M.E.R  Autrement}}",
        "Candidat De Marne Ecologie": "{{abréviation|ME|Marne Ecologie}}",
        "Resistance Citoyenne": "{{abréviation|RC|Résistance Citoyenne}}",
        "Nationalforum Elsab-Lothringen Unabhã„Gig": "{{abréviation|NEU|Nationalforum Elsab-Lothringen Unabhã„Gig}}",
        "Politique D'Action Citoyenne,Solidarite,": "{{abréviation|PACS|Politique d'action citoyenne, solidarité}}",
        "Ecologie Nouvelle": "{{abréviation|EN|Ecologie Nouvelle}}",
        "Union Des Victimes De L'Etat": "{{abréviation|UVE|Union des Victimes de l'Etat}}",
        "Union Des Retraites Et Independants": "{{abréviation|URI|Union des Retraites et Indépendants}}",
        "Des Animaux Et Mouvement Universaliste": "{{abréviation|AMU|Des animaux et mouvement universaliste}}",
        "Non Communique": "{{abréviation|NC|Non Communique}}",
        "Ecologie Citoyennete Et Laicite, Ecologie 92": "{{abréviation|ECLE92|Ecologie Citoyenneté et Laïcité, Ecologie 92}}",
        "France Folle": "{{abréviation|FF|France Folle}}",
        "Rassemblement P/La Democrat.&Civisme": "{{abréviation|RDC|Rassemblement pour la démocratie & civisme}}",
        "Des Idees Nouvelles": "{{abréviation|IN|Des idées nouvelles}}",
        "Union Democratie Et Libertes": "{{abréviation|UDL|Union démocratie et libertés}}",
        "Democratie Et Legitimite": "{{abréviation|DL|Démocratie et Légitimité}}",
        "Association Victimes Ciments Francais": "{{abréviation|AVCF|Association Victimes Ciments Français}}",
        "Parti Marginal Francais": "{{abréviation|MF|Parti Marginal Français}}",
        "Ecologie Pluraliste Independante": "{{abréviation|EPI|Ecologie Pluraliste Indépendante}}",
        "Groupement Politique Energies Democrates": "{{abréviation|GPED|Groupement Politique Energies Démocrates}}",
        "Renouveau De L'Assemblee Nationale": "{{abréviation|RAN|Renouveau de l'assemblée nationale}}",
        "Ecologie Independante": "{{abréviation|EI|Ecologie Indépendante}}",
        "Ras Le Bol": "{{abréviation|RB|Ras le bol}}",
        "Union Democratique Populaire": "{{abréviation|UDP|Union Démocratique Populaire}}",
        "Mouvement Social Democrate": "{{abréviation|MSD|Mouvement Social Démocrate}}",
        "National Aupres De La Federation Francaise De Judo": "{{abréviation|NFFJ|National auprès de la fédération Francaise de judo}}",
        "Ami Public": "{{abréviation|AP|Ami Public}}",
        "Collectif Républicain Et Citoyen": "{{abréviation|CRC|Collectif Républicain et Citoyen}}",
        "Parti Du Ras Le Bol": "{{abréviation|RB|Ras le bol}}",
        "Mouvement Ras Le Bol": "{{abréviation|RB|Ras le bol}}",
        "Organisation Contre Le Systeme Ena": "{{abréviation|OSENA|Organisation contre le systeme ENA}}",
        "Sos Syndic": "{{abréviation|SS|Sos Syndic}}",
        "Pour La Verite Et La Justice Des Scandales Du Sieds Et De La Regie Du Sieds": "{{abréviation|SIEDS|Pour la vérité et la justice des scandales du Sieds et de la régie du Sieds}}",
        "France Humaniste Et Visionniste": "{{abréviation|FHV|France Humaniste et Visionniste}}",
        "Candidat De L'Union Nationale Ecologiste": "{{abréviation|UNE|Union Nationale Ecologiste}}",
        "Stop A L'Autoroute": "{{abréviation|SA|Stop à l'autoroute}}",
        "Defense Des Animaux Et Collectif National Defense Animale": "{{abréviation|DACNDA|Défense des animaux et collectif national défense animale}}",
        "Candidate Du Parti Pour La Defense Des Animaux": "{{abréviation|PDA|Parti pour la défense des animaux}}",
        "Solidarité Liberté Justice Paix": "{{abréviation|SLJP|Solidarité Liberté Justice Paix}}",
        "Parti Pour La Defense Des Animaux Et Mouvement Universaliste": "{{abréviation|AMU|Des animaux et mouvement universaliste}}",
        "Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "{{abréviation|AMU|Des animaux et mouvement universaliste}}",
        "Parti Pour La Defense Des Animaux": "{{abréviation|PDA|Parti pour la défense des animaux}}",
        "Developpement Social Democratie De Proximite": "{{abréviation|DSDP|Développement Social Démocratie de Proximité}}",
        "Parti Des Socioprofessionnels": "{{abréviation|PS|Parti des socioprofessionnels}}",
        "Mouvement Pour Une Citoyennete Republicaine": "{{abréviation|MCR|Mouvement pour une Citoyenneté Républicaine}}",
        "Parti D'En Rire": "{{abréviation|PR|Parti d'en Rire}}",
        "Union Ecologiste Et Democratie": "{{abréviation|UED|Union Ecologiste et Démocratie}}",
        "Independant": "{{abréviation|IND|Independant}}",
        "Mouvement Regionaliste De Bretagne": "{{abréviation|MRB|Mouvement Régionaliste De Bretagne}}",
        "Rassemblement Pour L'Initiative Citoyenne": "{{abréviation|RIC|Rassemblement pour l'initiative citoyenne}}",
        "Rassemblement Pour Initiative Citoyenne": "{{abréviation|RIC|Rassemblement pour l'initiative citoyenne}}",
        "Rassemblement Des Savoisiens": "{{abréviation|RS|Rassemblement des savoisiens}}",
        "Gip - Democratie Active": "{{abréviation|GIP|GIP - Démocratie active}}",
        "La France En Action": "{{abréviation|FA|La France en action}}",
        "Le Parti De L'Alliance": "{{abréviation|PA|Le parti de l'alliance}}",
        "Union Nationale Ecologiste Sans Emploi": "{{abréviation|UNESE|Union nationale écologiste sans emploi}}",
        "Parti Des Droits De L'Homme": "{{abréviation|PDH|Parti des droits de l'Homme}}",
        "Solidaires Regions Ecologie": "{{abréviation|SRE|Solidaires régions écologie}}",
        "Vam (Voter Am)": "VAM",
        "Union Des Citoyens Independants": "{{abréviation|UCI|Union des citoyens independants}}",
        "Union Ecologie Et Democratie": "{{abréviation|UED|Union Ecologie et Démocratie}}",
        "Mouvement Union Ecologie Et Democratie": "{{abréviation|MUED|Mouvement Union Ecologie et Démocratie}}",
        "Divers": "{{abréviation|DIV|Divers}}",
        "Union Pour L'Ecologie Et La Democratie": "{{abréviation|UED|Union pour l'écologie et la démocratie}}",
        "Force De Rassemblement Republicaine Pour Une Citoyennete Plus Egale": "{{abréviation|FRRCE|Force de Rassemblement Republicaine pour une citoyennete plus égale}}",
        "Gard Fraternite": "{{abréviation|GF|Gard Fraternité}}",
        "Parti Du Vote Blanc": "{{abréviation|PVB|Parti du vote blanc}}",
        "Ligue Savoisienne": "{{abréviation|LS|Ligue Savoisienne}}",
        "Priorite Democratie En France": "{{abréviation|PDF|Priorité démocratie en France}}",
        "Pour Respect Droits Acquis Pour Savoie": "{{abréviation|RDAS|Pour respect droits acquis pour Savoie}}",
        "Parti Pirate": "[[Parti pirate (France)|PR]]",
        "Parti De La Nation Occitane": "[[Parti de la nation occitane|PNO]]",
        "Rassemblement Populaire Local": "{{abréviation|RPL|Rassemblement populaire local}}",
        "Reseau Nouvelle Donne": "[[Nouvelle Donne (parti politique)|ND]]",
        "Concordat Citoyen": "{{abréviation|CC|Concordat citoyen}}",
        "Region 93 Verte": "{{abréviation|R93V|Région 93 Verte}}",
        "Candidat Parachute": "{{abréviation|CP|Candidat Parachute}}",
        "Union Royaliste": "{{abréviation|UR|Union Royaliste}}",
        "Independant, Apolitique": "{{abréviation|IA|Indépendant, Apolitique}}",
        "Convergence Ecologie Solidarite": "{{abréviation|CES|Convergence écologie solidarité}}",
        "Parti Blanc": "{{abréviation|PB|Parti blanc}}",
        "Ordre Republicain Francais": "{{abréviation|ORF|Ordre républicain français}}",
        "Solidarite Ecologie Gauche Alternative": "{{abréviation|SEGA|Solidarite Ecologie Gauche Alternative}}",
        "Reformes, Democratie Sante": "{{abréviation|ORF|Réformes, démocratie santé}}",
        "Entreprise Emplois": "{{abréviation|EE|Entreprise emplois}}",
        "Alliance Pour L'Ecologie Et La Democratie": "{{abréviation|AED|Alliance pour l'écologie et la démocratie}}",
        "Droit De Chasse": "{{abréviation|DC|Droit de chasse}}",
        "Pour Les Droits D'Auteurs": "{{abréviation|DA|Pour les droits d'auteurs}}",
        "Union Des Ecologistes": "{{abréviation|UE|Union des écologistes}}",
        "Parti Ras Le Bol": "{{abréviation|PRB|Parti ras le bol}}",
        "L'Union Nationale Ecologiste Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "{{abréviation|UNE|Union Nationale Ecologiste}}-{{abréviation|PD|Parti pour la Défense}}-{{abréviation|MU|Mouvement Universaliste}}",
        "Union Nationale Ecologiste Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "{{abréviation|UNE|Union Nationale Ecologiste}}-{{abréviation|PD|Parti pour la Défense}}-{{abréviation|MU|Mouvement Universaliste}}",
        "Union Nationale Ecologiste, Le Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "{{abréviation|UNE|Union Nationale Ecologiste}}-{{abréviation|PD|Parti pour la Défense}}-{{abréviation|MU|Mouvement Universaliste}}",
        "Union Nationale Ecologiste, Parti Pour La Defense Des Animaux Et Le Mouvement Universaliste": "{{abréviation|UNE|Union Nationale Ecologiste}}-{{abréviation|PD|Parti pour la Défense}}-{{abréviation|MU|Mouvement Universaliste}}",
        "Union Nationale Ecologiste, Parti Pour La Defense Des Animaux Et Mouvement Universaliste": "{{abréviation|UNE|Union Nationale Ecologiste}}-{{abréviation|PD|Parti pour la Défense}}-{{abréviation|MU|Mouvement Universaliste}}",
        "Union Nationale Ecologie, Parti Pour La Defense Des Animaux Et Mouvement Universaliste": "{{abréviation|UNE|Union Nationale Ecologiste}}-{{abréviation|PD|Parti pour la Défense}}-{{abréviation|MU|Mouvement Universaliste}}",
        "Union Nationale Ecologiste": "{{abréviation|UNE|Union Nationale Écologiste}}",
        "Candidate De L'Union Nationale Ecologiste": "{{abréviation|UNE|Union Nationale Écologiste}}",
        "Ecologie Alternative Autogestion": "{{abréviation|EAA|Écologie alternative autogestion}}",
        "Rassemblement Des Democrates Et Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des démocrate et des républicains de progrès}}",
        "Rassemblement Des Democrate Et Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des démocrate et des républicains de progrès}}",
        "Le Parti De L'Arbre Pour La Sante De La Terre Des Hommes Et Des Generations Futures": "{{abréviation|PASTHGF|le Parti de l'Arbre pour la Santé de la Terre des Hommes et des Générations Futures}}",
        "Union Democratique Bretonne": "[[Union démocratique bretonne|UDB]]",
        "Parti De La Loi Naturelle (Pln)": "[[Parti de la loi naturelle|PLN]]",
    },
    "EXD": {
        "empty": "[[Extrême droite en France|EXD]]",
        "Extreme Droite": "[[Extrême droite en France|EXD]]",
        "Candidature Personnelle D Extreme Droite": "[[Extrême droite en France|EXD]]",
        "Mnr - Contre L'Immigration-Islamisation, L'Insecurite": "[[Mouvement national républicain|MNR]]",
        "Mnr - Contre L'Immigration-Islamisation": "[[Mouvement national républicain|MNR]]",
        "Mouvement National Republicain": "[[Mouvement national républicain|MNR]]",
        "Union De La Droite Nationale": "[[Union de la droite nationale|UDN]]",
        "Parti Anti-Sioniste": "[[Parti antisioniste|PAS]]",
        "Defendons La Chasse Et Nos Traditions": "{{abréviation|DCT|Défendons la chasse et nos traditions}}",
        "Rassemblement Republicain Pour L Union Centriste": "{{abréviation|RRUC|Rassemblement républicain pour l'union centriste}}",
        "Candidat Du Rassemblement Des Democrates Et Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des Démocrates et des Républicains de Progrés}}",
        "Candidate Du Rassemblement Des Democrates Et Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des Démocrates et des Républicains de Progrés}}",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Jeune Bretagne": "[[Jeune Bretagne|JB]]",
        "Bloc Identitaire": "[[Les Identitaires|BI]]",
        "Alliance Populaire": "{{abréviation|AP|Alliance Populaire}}",
        "Candidat D Opposition Unitaire Et Nationale": "{{abréviation|OUN|Opposition Unitaire et Nationale}}",
        "Mouvement De Rassemblement National": "{{abréviation|MRN|Mouvement de Rassemblement National}}",
        "Mouvement De Rassemblement National Alliance Populaire": "{{abréviation|MRNAP|Mouvement de Rassemblement National Alliance Populaire}}",
        "Alsace Debout Contre L'Insecurite Et L'Immigration": "{{abréviation|ADII|Alsace debout contre l'insécurité et l'immigration}}",
        "Parti National Radical": "{{abréviation|PNR|Parti National Radical}}",
        "Front Francais": "{{abréviation|FF|Front Français}}",
        "Liste D Entente Populaire Et Nationale": "{{abréviation|EPN|Liste d'entente populaire et nationale}}",
        "Les Francais D'Abord": "{{abréviation|FA|Les Français d'Abord}}",
        "Trop D'Immigres, La France Aux Francais": "{{abréviation|IFF|Trop d'immigrés, la France aux Francais}}",
        "Trop D Immigres La France Aux Francais": "{{abréviation|IFF|Trop d'immigrés, la France aux Francais}}",
        "Alternative Nationale": "{{abréviation|AN|Alternative Nationale}}",
        "Savoie Independante": "{{abréviation|SI|Savoie Indépendante}}",
        "Nouvelle Solidarite": "{{abréviation|NS|Nouvelle Solidarité}}",
        "Halte A L'Immigration": "{{abréviation|HI|Halte à l'immigration}}",
        "Parti Communautaire National Europeen": "{{abréviation|PCNE|Parti communautaire national européen}}",
        "Parti National Republicain": "{{abréviation|PNR|Parti national républicain}}",
        "Parti Ouvrier Europeen": "[[Parti ouvrier européen|POE]]",
        "Parit Ouvrier Europeen": "[[Parti ouvrier européen|POE]]",
        "Federation Nationale Des Independants": "[[Fédération nationale des indépendants|FNI]]",
        "Solidarite Et Progres": "{{abréviation|SP|Solidarité et Progrès}}",
        "Halte A L'Immigration Avec L'Alliance Populaire": "{{abréviation|HIAP|Halte à l'Immigration avec l'Alliance Populaire}}",
        "Parti Populaire Français": "{{abréviation|PPF|Parti Populaire Français}}",
        "Union Des Independants": "{{abréviation|UI|Union des indépendants}}",
        "Mouvement Travail Patrie": "{{abréviation|MTP|Mouvement Travail Patrie}}",
        "Universelle Fondation Drogues, Crimes Contre L'Humanite": "{{abréviation|UFDCCH|Universelle Fondation Drogues, Crimes Contre L'Humanite}}",
        "Alliance Populaire, Mouvement De Rassemblement National": "{{abréviation|AP|Alliance populaire}} - {{abréviation|MRN|Mouvement de rassemblement national}}",
        "Alliance Populaire, Rassemblement Des Forces Nationales": "{{abréviation|AP|Alliance populaire}} - {{abréviation|MRN|Mouvement de rassemblement national}}",
        "Candidate De L'Alliance Populaire": "{{abréviation|AP|Alliance populaire}}",
        "Mouvement Alliance Populaire": "{{abréviation|AP|Alliance populaire}}",
        "Halte A L'Immigration Mais Dans La Dignite": "{{abréviation|HID|Halte à l'immigration mais dans la dignité}}",
        "La France Aux Francais Trop D'Immigres": "{{abréviation|FFI|La France aux français trop d'immigrés}}",
        "Rassemblement Des Democrates Et Des Republicains De Progres": "{{abréviation|RDRP|Rassemblement des démocrates et des républicains de progrès}}",
        "Rassemblement Des Democrates Et Des Republicains Des Progres": "{{abréviation|RDRP|Rassemblement des démocrates et des républicains de progrès}}",
        "Rassemblement Des Forces Nationales Presente Par L'Alliance Populaire": "{{abréviation|RFNAP|Rassemblement des forces nationales présenté par l'alliance populaire}}",
        "Parti De La Loi Naturelle": "[[Parti de la loi naturelle|PLN]]",
        "Parti Pour La Loi Naturelle": "[[Parti de la loi naturelle|PLN]]",
        "Candidat De L'Alliance Populaire": "{{abréviation|AP|Alliance populaire}}",
    },
    "ECO": {
        "Ecologiste": "[[Écologisme|ECO]]",
        "Ecologie": "[[Écologisme|ECO]]",
        "Autre Ecologiste": "[[Écologisme|ECO]]",
        "empty": "[[Écologisme|ECO]]",
        "Génération Écologie": "[[Génération écologie|GE]]",
        "Generation Ecologie": "[[Génération écologie|GE]]",
        "Les Verts": "[[Les Verts (France)|LV]]",
        "Les Verts Soutien Parti Socialiste": "[[Les Verts (France)|LV]]-[[Parti socialiste (France)|PS]]",
        "Rassemblement La Gauche Avec Les Verts": "[[Les Verts (France)|LV]]",
        "Ecologie Les Verts": "[[Les Verts (France)|LV]]",
        "Sans Etiquette": "[[Sans étiquette|SE]]",
        "Europe-Ecologie-Les Verts": "[[Europe Écologie Les Verts|EELV]]",
        "Europe-Ecologie-Les Verts (Soutien Ps)": "[[Europe Écologie Les Verts|EELV]]-[[Parti socialiste (France)|PS]]",
        "Alliance Ecologiste Indépendante": "[[Alliance écologiste indépendante|AEI]]",
        "Le Trefle": "[[Le Trèfle - Les nouveaux écologistes|Le Trèfle]]",
        "Le Trèfle - Les Nouveaux Ecologistes": "[[Le Trèfle - Les nouveaux écologistes|Le Trèfle]]",
        "Le Trefle - Les Nouveaux Ecologistes": "[[Le Trèfle - Les nouveaux écologistes|Le Trèfle]]",
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Les Nouveaux Ecologistes Hommes Nature Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Nouv. Ecolo. Rassembl. Nature&Animaux": "[[Le Trèfle - Les nouveaux écologistes|NERNA]]",
        "Mouvement Écologiste Indépendant": "[[Mouvement écologiste indépendant|MEI]]",
        "Mouvement Ecologiste Independant": "[[Mouvement écologiste indépendant|MEI]]",
        "Mouvement Hommes Animaux Nature": "[[Mouvement hommes animaux nature|MHAN]]",
        "Mouvement Homme Nature Animaux": "[[Mouvement hommes animaux nature|MHAN]]",
        "Mouvement Hommes-Animaux-Nature : Mhan": "[[Mouvement hommes animaux nature|MHAN]]",
        "Mouvement Des Ecologistes Independants": "[[Mouvement écologiste indépendant|MEI]]",
        "Cap 21": "[[Cap21]]",
        "Citoyennete Action Pour Le 21E Siecle": "[[Cap21]]",
        "Citoyennete Action Participation Pour Le 21E Siecle": "[[Cap21]]",
        "Une France Humaine": "{{abréviation|FH|Une France Humaine}}",
        "Union Des Ecologistes En Seine Maritime": "{{abréviation|UESM|Union des Ecologistes en Seine Maritime}}",
        "Ecologie Pour L Alsace Du Nord": "{{abréviation|FH|Écologie pour l'Alsace du nord}}",
        "Ecologie Artisanale": "{{abréviation|EA|Écologie Artisanale}}",
        "Ecologie Europe 92": "{{abréviation|EE92|Ecologie Europe 92}}",
        "Union Des Ecologistes Haut-Alpins": "{{abréviation|UEHA|Union des écologistes Haut-Alpins}}",
        "Generation Ecologie Les Bleus	": "[[Génération écologie|GE]]-{{abréviation|LB|Les Bleus}}",
        "Ecologie Nature Environnement": "{{abréviation|ENE|Ecologie Nature Environnement}}",
        "Verts Alternatifs": "{{abréviation|VA|Verts Alternatifs}}",
        "Verte Alternative": "{{abréviation|VA|Verts Alternatifs}}",
        "Mouvement Guadeloupeen Et Ecologiste": "{{abréviation|MGE|Mouvement guadeloupéen et écologiste}}",
        "Villes Vertes 94": "{{abréviation|VV94|Villes vertes 94}}",
        "Pour Ecologie Independante Et Proximite": "{{abréviation|EIP|Ecologie indépendante et proximité}}",
        "Parti Vert": "{{abréviation|PV|Parti Vert}}",
        "Ecologie, Renovation, Europe": "{{abréviation|ERE|Ecologie, Rénovation, Europe}}",
        "Pour Une Alternative Ecologiste, Citoyenne Et Progressiste": "{{abréviation|AECP|Pour une Alternative Ecologiste, Citoyenne et Progressiste}}",
        "Republique Ecologie Democratie": "{{abréviation|RED|République Ecologie Démocratie}}",
        "Ecologie Et Democratie": "{{abréviation|ED|Ecologie et démocratie}}",
        "Anjou Ecologie Autogestion": "{{abréviation|AEA|Anjou Ecologie Autogestion}}",
        "Union Nationale Ecologiste": "{{abréviation|UNE|Union nationale écologiste}}",
        "Limousin Ecologie": "{{abréviation|LE|Limousin Ecologie}}",
        "Essonne Verte": "{{abréviation|EV|Essonne Verte}}",
        "Vivre Ensemble Dans Une Meuse Propre": "{{abréviation|VEMP|Vivre ensemble dans une Meuse propre}}",
        "Les Ecologistes Regionalistes Solidaires Et Citoyens": "{{abréviation|ERSC|Les Écologistes Régionalistes Solidaires et Citoyens}}",
        "Ecologie Et Citoyens": "{{abréviation|EC|Ecologie et citoyens}}",
        "Eden-Republique Et Democratie": "{{abréviation|EDEN-RD|Eden-République et démocratie}}",
        "Ecologiste Independant": "{{abréviation|EI|Ecologiste indépendant}}",
        "Ecologie Alternative Pour Une Nouvelle Politique A Gauche": "{{abréviation|EANPG|Ecologie alternative pour une nouvelle politique à gauche}}",
        "Ecologie Sociale": "{{abréviation|ES|Ecologie Sociale}}",
        "Socialisme, Ecologie, Solidarite": "{{abréviation|SES|Socialisme, écologie, solidarité}}",
        "Parti Ecologiste": "[[Parti écologiste|PE]]",
        "Renouveau Ecologique": "{{abréviation|RE|Renouveau écologique}}",
        "Rassemblement Et Solidarite": "{{abréviation|RS|Rassemblement et Solidarité}}",
        "Paris Oxygene": "{{abréviation|PO|Paris Oxygène}}",
        "Nouveaux Ecologistes": "{{abréviation|NE|Nouveaux écologistes}}",
        "Confederation Des Ecologistes Independants": "{{abréviation|CEI|Confédération des écologistes indépendants}}",
        "Souverainete Ecologie Ruralite": "{{abréviation|SER|Souveraineté écologie ruralité}}",
        "Ecologie Et Citoyens-Solidaires-Regions-Ecologie": "{{abréviation|ECSRE|Ecologie et Citoyens-Solidaires-Régions-Ecologie}}",
        "Parti Pour La Defense Des Animaux": "{{abréviation|DA|Parti pour la défense des animaux}}",
        "Ensemble, Ecologistes Et Solidaires": "{{abréviation|EES|Ensemble, Écologistes et Solidaires}}",
        "Candidat Libre Pour Le Respect De L'Electeur": "{{abréviation|CLRE|Candidat libre pour le respect de l'électeur}}",
        "Solidarite Ecologie Gauche Alternative": "[[Les Alternatifs|SEGA]]",
        "Parti De L Entente": "{{abréviation|PE|Parti de l'entente}}",
    },
    "COM": {
        "empty": "[[Communisme|COM]]",
        "Communistes": "[[Communisme|COM]]",
        "Communiste": "[[Communisme|COM]]",
        "Parti Communiste Guadeloupeen ": "[[Parti communiste guadeloupéen|PCG]]",
        "Parti Communiste Guadeloupeen": "[[Parti communiste guadeloupéen|PCG]]",
        "Parti Communiste Martiniquais": "[[Parti communiste martiniquais|PCM]]",
        "Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Partie Communiste Francais": "[[Parti communiste français|PCF]]",
        "Parti Comâ­Muniste Francais": "[[Parti communiste français|PCF]]",
        "Parti Commuâ­Niste Francais": "[[Parti communiste français|PCF]]",
        "Communiste Francais ": "[[Parti communiste français|PCF]]",
        "Forces De Gauche Pcf": "[[Parti communiste français|PCF]]",
        "Pcf - Antiliberaux": "[[Parti communiste français|PCF]]",
        "Parti Communiste Francais Dissident": "[[Parti communiste français|PCF]]",
        "Candidate De Rassemblement Des Forces De Gauche Presentee Par Le P C F": "[[Parti communiste français|PCF]]",
        "Apparente Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Candidat Des Forces De Gauches Presente Par Le P C F": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Presente Par Le Parti Comâ­Muniste Francais": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Presente Par Le Pcf": "[[Parti communiste français|PCF]]",
        "Rassemblement Des Forces De Gauche Presente Par Le P C F": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Des Forces De Gauche Presente Par Le Pcf": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Pour Faire Du Neuf Avec Vous Pour La France, Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Des Forces De Gauche Presente Par Le P C F": "[[Parti communiste français|PCF]]",
        "Candidat Du Rassemblement A Gauche Pour Une Autre Politique Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Candidat De Ressemblement Des Forces De Gauche Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Des Forces De Progres Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Candidat De Rassemblement Pour Se Defendre Et Faire Du Neuf Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Rassemblement Des Forces De Gauche Presente Par Le Parti Comministe Francais": "[[Parti communiste français|PCF]]",
        "Parti Communiste Francais Agent Specialise D'Ecole Maternelle": "[[Parti communiste français|PCF]]",
        "Rassemblement Pour Se Defendre Et Faire Du Neuf Presentee Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Rassemblement Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Rassemblement Pour Se Defendre Et Faire Du Neuf Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Presentee Par Le Parti Communiste Francais Se Rassembler Pour Se Defendre Et Faire Du Neuf": "[[Parti communiste français|PCF]]",
        "Candidat Du Rassemblement Des Forces De Progres Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Rassemblement Des Forces De Gauche Presente Par Le Pcf": "[[Parti communiste français|PCF]]",
        "Rassemblement Des Forces De Gauche Presente Par Le Parti Communiste Francais": "[[Parti communiste français|PCF]]",
        "Parti Communiste Francais Pour Le Rassemblement Des Forces Progressistes Et Le Changement": "[[Parti communiste français|PCF]]",
        "Parti Communiste Francais, Pour Le Rassemblement Des Forces Progressistes Et Le Changement": "[[Parti communiste français|PCF]]",
        "Parti Communiste Francais Candidat De Rassemblement Pour Un Vrai Changement": "[[Parti communiste français|PCF]]",
        "Rassemblement Des Forces De Progres Presente Par Le Parti Communiste Francais Et Des Personnalites D'Opinions Diverses": "[[Parti communiste français|PCF]]",
        "Parti Communiste Francais ": "[[Parti communiste français|PCF]]",
        "Pour Le Rassemblement Des Forces De Progres Presentee Par Le Parti Communiste Francais Soutenue Par Les Personnalites De Nanterre Et Suresnes": "[[Parti communiste français|PCF]]",
        "Authentique Alternative De Gauche, Parti Communiste Francais": "{{abréviation|AAG|Authentique Alternative de Gauche}}-[[Parti communiste français|PCF]]",
        "Parti Communiste": "[[Parti communiste français|PCF]]",
        "Rassemblement Gauche Unie Et Anti Liberale": "[[Gauche antilibérale|RGUAL]]",
        "Gauche Antiliberale": "[[Gauche antilibérale|GA]]",
        "Candidat Rassemblement Pcf": "[[Parti communiste français|PCF]]",
        "Gauche Alternative Et Antiliberale": "[[Gauche antilibérale|GA]]",
        "Rassemblement Des Forces De Gauche": "{{abréviation|RFG|Rassemblement des forces de gauche}}",
        "Rassemblement Des Citoyens Pour Le Progres": "{{abréviation|RCP|Rassemblement des citoyens pour le progrès}}",
        "Rassemblement Pour La Gauche": "{{abréviation|RG|Rassemblement pour la gauche}}",
        "Mouvement Refondations": "{{abréviation|MR|Mouvement Refondations}}",
        "Communiste Renovateur": "{{abréviation|CR|Communiste Rénovateur}}",
        "Gauche Unie Antiliberale": "{{abréviation|GUA|Gauche Unie Antilibérale}}",
        "Candidat Du Rassemblement Et Des Forces De Progres": "{{abréviation|RFP|Rassemblement et des forces de progrès}}",
        "Collectif Unitaire Antiliberal": "{{abréviation|CUA|Collectif Unitaire Antilibéral}}",
        "Candidate Du Rassemblement Et Des Forces De Progres": "{{abréviation|RFP|Rassemblement et des forces de progrès}}",
        "Gauche Populaire Et Antiliberale Soutenue Par Pcf": "{{abréviation|GPA|Gauche populaire et antilibérale - PCF}}",
    },
}

# Nuance -> (couleur par défaut, {étiquette : code couleur})
COULEURS_ETIQUETTES = {
    "EXG": ("EXG", {
        "Lutte Ouvriere": "LO",
        "Lutte Ouvrière": "LO",
        "Mouvement Pour Un Parti Des Travailleurs (Mppt)": "MPPT",
        "Ligue Communiste Revolutionnaire": "LCR",
        "Nouveau Parti Anticapitaliste": "NPA",
        "Parti Des Travailleurs": "PT",
        "Parti Ouvrier Indépendant": "POI",
        "Communistes": "COM",
    }),
    "DVD": ("DVD", {
        "Mouvement Pour La France": "MPF",
        "Centre National Des Independants Et Paysans": "CNIP",
        "Centre National Des Independants": "CNIP",
        "Debout La Republique": "DLF",
        "Centre National Des Independants Et Paysans (Cnip)": "CNIP",
        "Debout La République": "DLF",
        "Parti Chrétien-Démocrate": "PCD",
        "Union Républicaine Populaire": "UPR",
        "Rassemblement Pour La France": "RPF",
        "Union Des Démocrates Pour La République": "UDR",
        "Rassemblement Pour La Republique": "RPR",
    }),
    "DVG": ("DVG", {
        "Socialiste Dissidente": "PS",
        "empty": "DVG",
        "Rassemblement Démocratrique Martiniquais": "RDM",
        "Mouvement Des Citoyens": "MDC",
        "Energie Radicale": "PRG",
        "Bâtir Le Pays Martinique": "BPM",
        "Mouvement Républicain Et Citoyen": "MRC",
        "Guadeloupe Unie Socialisme Et Realites": "GUSR",
        "Parti Progressiste Et Democratique Guadeloupeen": "PPDG",
        "Parti Socialiste": "PS",
    }),
    "DIV": ("DIV", {
        "Les Nouveaux Ecologistes Du Rassemblement Nature Et Animaux": "ECO",
        "Chasse Peche Nature Et Traditions": "CPNT",
        "Chasse Peche Nature Traditions": "CPNT",
        "Parti Occitan": "REG",
        "Parti Pirate": "violet",
        "Sans Etiquette": "SE",
        "Sans Étiquette": "SE",
        "Mouvement Indépendantiste Martiniquais": "MIM",
        "Regionalistes": "REG",
        "Reseau Nouvelle Donne": "fuchsia",
        "Union Democratique Bretonne": "UDB",
    }),
    "EXD": ("EXD", {
        "Mouvement National Republicain": "MNR",
        "Mnr - Contre L'Immigration-Islamisation, L'Insecurite": "MNR",
        "Mnr - Contre L'Immigration-Islamisation": "MNR",
    }),
    "ECO": ("ECO", {
        "Generation Ecologie": "GE",
        "Les Verts": "Verts",
        "Europe-Ecologie-Les Verts": "EELV",
        "Alliance Ecologiste Indépendante": "AEI",
        "Mouvement Ecologiste Independant": "MEI",
        "Mouvement Écologiste Indépendant": "MEI",
    }),
    "COM": ("COM", {
        "Parti Communiste Guadeloupeen ": "PCG",
        "Parti Communiste Guadeloupeen": "PCG",
    }),
}


def couleur(code):
    """Renvoie le modèle de couleur Wikipédia correspondant à ``code``."""
    return MODELE_COULEUR.format(code)


def parti_ancien(nuance):
    """Libellé et couleur d'une colonne de nuance des fichiers 1958-1981.

    Renvoie ``("error", "error")`` si la nuance est inconnue.
    """
    if nuance not in NUANCES_ANCIENNES:
        return "error", "error"
    libelle, code = NUANCES_ANCIENNES[nuance]
    return libelle, couleur(code)


def parti_recent(nuance, etiquette):
    """Libellé et couleur d'un candidat des fichiers 1988-2012.

    ``nuance`` est le code de nuance du CDSP (seul le début est utilisé) et
    ``etiquette`` l'étiquette déclarée par le candidat, mise en forme avec
    ``str.title()`` (ou :data:`ETIQUETTE_VIDE`).
    Une valeur inconnue est signalée par ``"error"``.
    """
    for prefixe, (libelle, code) in PREFIXES_SPECIAUX.items():
        if nuance.startswith(prefixe):
            return libelle, couleur(code)

    nuance = nuance[:3]
    if nuance in PARTIS_RECENTS:
        libelle = PARTIS_RECENTS[nuance]
    elif nuance in ETIQUETTES:
        libelle = ETIQUETTES[nuance].get(etiquette, etiquette)
    else:
        libelle = "error"

    if nuance in COULEURS_RECENTES:
        code = couleur(COULEURS_RECENTES[nuance])
    elif nuance in COULEURS_ETIQUETTES:
        defaut, table = COULEURS_ETIQUETTES[nuance]
        code = couleur(table.get(etiquette, defaut))
    else:
        code = "error"
    return libelle, code
